-- Crear la tabla SyncLogs manualmente si no existe
CREATE TABLE IF NOT EXISTS "SyncLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Direction" text NOT NULL,
    "SyncedAt" timestamp with time zone NOT NULL,
    "ConflictPolicy" text NOT NULL,
    "ItemsCreated" integer NOT NULL,
    "ItemsUpdated" integer NOT NULL,
    "ConflictsResolved" integer NOT NULL,
    CONSTRAINT "PK_SyncLogs" PRIMARY KEY ("Id")
);
